### ISSUE TITLE
example doesn't work anymore

### ISSUE THREAD

**Issue by VincentGuyader** [ThinkR-open/collage#20]
```
library(magick)
library(collage)
tigrou <- image_read( system.file("tigrou", "tigrou.jpg", package = "collage") )
collage( tigrou, tiles = kittens, size = 10)
```

![image](https://user-images.githubusercontent.com/10470699/40578691-8d1ef208-6118-11e8-99c9-42c97601fd90.png)

**Comment by jeroen** [comment]
Uhoh did I break something?

**Comment by VincentGuyader** [comment]
Dont know if it's a magick or a dplyr issue
It was ok, 2 or 3 weeks ago.
@romainfrancois can you have a look at this ? 

:)

**Comment by jeroen** [comment]
Looks like this broke in the update from magick 1.5 -> 1.6... let me see what changed.

**Comment by VincentGuyader** [comment]
thanks a lot @jeroen :)
